# Environmental Science Lab
## Training exercise

** Your given and family name: ** 
** Date: dd.mm.yyyy ** 

---
## 1) Objective
...

## 2) Experimental Setup
- ...

## 3) Procedure
1) ...
2) ...

In [85]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Enter your measured data in [mm]
l = 57
w = 6.3

# Enter your estimated uncertainties in [mm]
dl = 1
dw = 0.05

A = l*w
dll = dl / l
dww = dw / w
dAA = dll + dww

dA = A * dAA

print(f"Measured length l = {l:.6g} mm +- {dl:.6g} mm")
print(f"Measured length w = {w:.6g} mm +- {dw:.6g} mm")
print(f"Relative uncertainties dl/l = {dll*100:.0f}%  dw/w =  {dww*100:.0f} %")
print(f"Relative uncertainty on measured surface dA/l = dl/l + dw/w = {dAA*100:.0f}%")
print(f"=========")
print(f"Measured surface A = {A:.1f} mm2 +- {dA:.1f} mm2")

Measured length l = 57 mm +- 1 mm
Measured length w = 6.3 mm +- 0.05 mm
Relative uncertainties dl/l = 2%  dw/w =  1 %
Relative uncertainty on measured surface dA/l = dl/l + dw/w = 3%
=========
Measured surface A = 359.1 mm2 +- 9.1 mm2

## 5) Show results as table

In [95]:
x = [l,w,A]
dx = [dl,dw,dA]
dxx = [dll*100,dww*100,dAA*100]

names = ["Length", "Width", "Area"]
units = ["mm", "mm", "mm2"]
units2 = ["%", "%", "%"]

df = pd.DataFrame({
    "Quantity": names,
    "Value": x,
    "Uncertainty": dx,
    "Unit": units,
    "Rel. uncertainty": dxx,
    "Rel. unc. unit": units2
})
df["Value"] = df["Value"].apply(lambda x: f"{x:.2f}")
df["Uncertainty"] = df["Uncertainty"].apply(lambda x: f"{x:.2f}")
df["Rel. uncertainty"] = df["Rel. uncertainty"].apply(lambda x: f"{x:.02f}")
df

  Quantity   Value Uncertainty Unit Rel. uncertainty Rel. unc. unit
0   Length   57.00        1.00   mm             1.75              %
1    Width    6.30        0.05   mm             0.79              %
2     Area  359.10        9.15  mm2             2.55              %

## 6) Measure a denstiy

In [96]:
# Enter your measured data in [mm]
# in this example the object has a cylindrical shape
d = 35.2
L = 75.2
V = np.pi * (d/2)**2 * L
# measured mass in [g]
M = 145.23

# Enter your estimated uncertainties in [mm]
dd = 0.05
dL = 0.05
dM = 0.01

dLL = dL / L
ddd = dd / d
dMM = dM / M
dVV = dLL + 2*ddd
dV = V * dVV

# density in g / mL (g/cm3)
rho = M/(V/1000)
drho = rho * (dVV + dMM)

print(f"Measured diameter d = {d:.6g} mm +- {dd:.6g} mm")
print(f"Measured length L = {L:.6g} mm +- {dL:.6g} mm")
print(f"Measured mass M = {M:.6g} g +- {dM:.6g} g")
print(f"Relative uncertainties dL/L = {dLL*100:.1f}%  dd/d =  {ddd*100:.1f} %")
print(f"Relative uncertainty dM/M = {dMM*100:.1f}%")
print(f"Relative uncertainty on measured volume dV/V = dL/L + 2 dd/d = {dVV*100:.1f}%")
print(f"=========")
print(f"Measured volume V = {V/1000:.0f} mL +- {dV:.0f} mm2")
print(f"Measured density rho = {rho:.03f} g/mL +- {drho:.2f} g/mL")

Measured diameter d = 35.2 mm +- 0.05 mm
Measured length L = 75.2 mm +- 0.05 mm
Measured mass M = 145.23 g +- 0.01 g
Relative uncertainties dL/L = 0.1%  dd/d =  0.1 %
Relative uncertainty dM/M = 0.0%
Relative uncertainty on measured volume dV/V = dL/L + 2 dd/d = 0.4%
=========
Measured volume V = 73 mL +- 257 mm2
Measured density rho = 1.985 g/mL +- 0.01 g/mL

## 7) Show results as table

In [97]:
x = [d,L,M,V/1000,rho]
dx = [dd,dL,dM,dV/1000,drho]
dxx = [dLL*100,ddd*100,dMM*100,dVV*100,dVV*100 + dMM*100]
units = ["mm","mm","g","mL","g/mL"]

names = ["Diameter", "Legth", "Mass","Volume","Density"]
units2 = ["%", "%", "%","%", "%"]

df = pd.DataFrame({
    "Quantity": names,
    "Value": x,
    "Uncertainty": dx,
    "Unit": units,
    "Rel. uncertainty": dxx,
    "Rel. unc. unit": units2
})
df["Value"] = df["Value"].apply(lambda x: f"{x:.2f}")
df["Uncertainty"] = df["Uncertainty"].apply(lambda x: f"{x:.2f}")
df["Rel. uncertainty"] = df["Rel. uncertainty"].apply(lambda x: f"{x:.2f}")
df

   Quantity   Value Uncertainty  Unit Rel. uncertainty Rel. unc. unit
0  Diameter   35.20        0.05    mm             0.07              %
1     Legth   75.20        0.05    mm             0.14              %
2      Mass  145.23        0.01     g             0.01              %
3    Volume   73.18        0.26    mL             0.35              %
4   Density    1.98        0.01  g/mL             0.36              %

---
### IMPORTANT: Before closing the browser
Go to **File → Download → Notebook (.ipynb)** to save your work.